### ISSUE TITLE
Invalid Config

### ISSUE THREAD

**Issue by magnusthornberg** [DSorlov/swemail#26] opened 2023-06-12 12:20 UTC
My integration says invalid configuration an it does not loss

Log Details (ERROR)

Logger: homeassistant.setup
Source: setup.py:215 
First occurred: 09:00:24 (1 occurrences) 
Last logged: 09:00:24

Setup failed for custom integration swemail: Unable to import component: Exception importing custom_components.swemail

This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/swemail/__init__.py:20 
Integration: Svensk Postutdelning (documentation, issues) 
First occurred: 09:00:24 (1 occurrences) 
Last logged: 09:00:24

Unexpected exception importing component custom_components.swemail
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/swemail/__init__.py", line 20, in <module>
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'

**Comment by thulin82** [comment] 2023-06-12 12:32
`@asyncio.coroutine
^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'`

Looks like the problem that was solved in 1.0.7. Try update!

**Comment by magnusthornberg** [comment] 2023-06-12 14:25
It’s working now

**Comment by DSorlov** [comment] 2023-06-12 18:01
Duplicate of #23

**Closed by DSorlov** 2023-06-12 18:02 UTC
