### ISSUE TITLE
Number of days left not translated

### ISSUE THREAD

**Issue by swemaverick** [DSorlov/swemail#22] opened 2023-05-17 17:52 UTC
Just found and installed this plugin. It's downloading the values correctly, but not translating it to how many days left so what I see in the sensor is not "Today", I see 0. Tested both swedish and english UI, also can see the translation files in the folder structure so they are in there. Any good way of troubleshooting and making the translations to fly? One of the pictures for PostNord sensor and one for City mail so therefor the number 0 don't align so you don't wonder..

<img width="510" alt="image" src="https://github.com/DSorlov/swemail/assets/122382656/ae7adc07-8711-47fc-8149-bd67dfbb9736">
<img width="527" alt="image" src="https://github.com/DSorlov/swemail/assets/122382656/351e1c40-c371-44fa-8c98-2324194ae997">

**Comment by thulin82** [comment] 2023-05-18 08:02
Duplicate of #19, fixed in #20

**Comment by swemaverick** [comment] 2023-05-19 05:51
The install is fresh since 2 days, should that use the latest files then? Downloaded the latest sv.json and en.json and restarted HA without any improvement. How do I enable/update/pull the latest into Hacs and makes it work?

**Comment by thulin82** [comment] 2023-05-19 06:18
> The install is fresh since 2 days, should that use the latest files then? Downloaded the latest sv.json and en.json and restarted HA without any improvement. How do I enable/update/pull the latest into Hacs and makes it work?

The issue is fixed, but no new release has been made by the author. Either you wait for that to happen (the release will probably be named 1.0.6), and update through HACS. Or like someone mentioned in #19, you can always update the files manually (which it looks like you tried, but there are also an update to sensor.py file)

**Comment by swemaverick** [comment] 2023-05-19 06:23
Updated the sensor file as well and restarted, now it works until the next update, thanks!!

**Comment by DSorlov** [comment] 2023-05-19 06:34
Sorry! Fixed! New release done!

**Closed by DSorlov** 2023-05-19 06:34 UTC
